language: ruby
before_install:
  - gem install bundler

bundler_args: --without development
cache:
  - bundler
  - apt

rvm:
  - 2.5
  - 2.6
  - 2.7
services:
  - mongodb


gemfile:
  - gemfiles/mongoid6.gemfile
  - gemfiles/mongoid7.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
